image:
  repository: ostudent826/devops_experts_project
  tag: mysql-v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306
  externalPort: 3307

mysql:
  rootPassword: 123456
  database: users
  user: root
  userPassword: 123456

persistence:
  enabled: true
  mountPath: /var/lib/mysql
  size: 1Gi
  storageClass: ""

